### ISSUE TITLE
0.3.2

### ISSUE THREAD

**Issue by vipinpaul** [bible-technology/scribe-docs#11]
- Rearranging the sidebar

**Comment by selvabenz** [comment]
Sidebar Content 

* Getting Started
** What is Scribe SE? # Mention that hereafter in this document the app will be referred to as just 'Scribe'.
** System Requirements
** Installation
** Create a New Account
* Basic Setup
** Profile
** App Language
** Notifications
* Manage Project
** Create a Project
*** Advanced Settings
** Projects # Talks about listing, starring, searching and sorting
*** Edit Project Details
*** Import Project
*** Archive Project
*** Export Project
*** Backup and Sync
*** Sync
* Modes # Overview of the concept of modes.
** Common Functionality
*** Layout # Adding columns and sections.
*** Resources # Importing resources, resource management, etc.
*** Menu Bar
*** Font Size
*** Sync
** Text Bible Translation
*** Editing Text # Example of drafting a few verses. Say data is stored in the backend as USFM.
*** Scroll Lock
*** Bookmarks
** Oral Bible Translation
*** Audio Toolbar # Describe functions of each of the buttons and settings on the toolbar
** Open Bible Stories
*** Drafting # Example of drafting a story.
* Other Features
** # Anything that does not cleanly fit in the above categories
* More Information
* Technical Support

**Comment by vipinpaul** [comment]
closed
