### ISSUE TITLE
Scribe document

### ISSUE THREAD

**Issue by AnnCherianA** [bible-technology/scribe-docs#2]
User guide for Scribe

**Comment by AnnCherianA** [comment]
@SeemaNandihal please update the link of the scribe document you are working on in the description

**Comment by AnnCherianA** [comment]
> @SeemaNandihal please update the link of the scribe document you are working on in the description
Please update the document as mentioned above
@SeemaNandihal

**Comment by vipinpaul** [comment]
Its done https://scribe-editor-docs.netlify.app/
